import { defineConfig, type Plugin } from "vitest/config";
import preact from "@preact/preset-vite";
import { readdirSync } from "node:fs";
import { createHash } from "node:crypto";

// Writes dist/sw.js: a small service worker that precaches every built file, so the app
// opens with no signal at all (the team data itself is cached separately, in IndexedDB).
// It only handles this app's own files — requests to Google are never cached.
function serviceWorker(): Plugin {
  return {
    name: "rock-team-sw",
    apply: "build",
    generateBundle(_opts, bundle) {
      const files = ["./", ...Object.keys(bundle), ...readdirSync("public")].map((f) => (f === "./" ? f : "./" + f));
      const version = createHash("sha256").update(files.join("|") + Object.values(bundle).map((c) => ("code" in c ? c.code : String(c.source))).join("")).digest("hex").slice(0, 12);
      this.emitFile({
        type: "asset",
        fileName: "sw.js",
        source: `// generated by vite.config.ts — do not edit
const CACHE = "rock-team-${version}";
const FILES = ${JSON.stringify(files)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith("rock-team-") && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    // The page itself: use the network when it answers quickly (to pick up new versions),
    // otherwise the cached copy — a gym with one bar of signal shouldn't mean a blank screen.
    e.respondWith((async () => {
      const cached = await caches.match("./", { cacheName: CACHE });
      const network = fetch(req).then((res) => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put("./", copy)); }
        return res;
      });
      if (!cached) return network;
      const timeout = new Promise((resolve) => setTimeout(() => resolve(cached), 2500));
      return Promise.race([network.catch(() => cached), timeout]);
    })());
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`,
      });
    },
  };
}

// base "./" so the built app works from any sub-path (e.g. GitHub Pages /repo-name/).
export default defineConfig({
  base: "./",
  plugins: [preact(), serviceWorker()],
  test: { environment: "node" },
});
