// Runs after `expo export -p web` (npm run build:web). Turns dist/ into an installable,
// offline-capable web app:
// - a web app manifest + home-screen icons, linked from index.html,
// - sw.js, a service worker that precaches every exported file so the app opens with no
//   signal (team data is cached separately, in IndexedDB); requests to Google are never cached,
// - 404.html, a copy of index.html, so static hosts like GitHub Pages serve deep links,
//   and .nojekyll so GitHub Pages doesn't hide the _expo folder.

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync, copyFileSync } from "node:fs";
import { join, relative } from "node:path";

const DIST = new URL("../dist/", import.meta.url).pathname;
const base = (process.env.WEB_BASE_URL ?? "").replace(/\/?$/, "/"); // "/" or "/rock-team/"

function walk(dir) {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

writeFileSync(join(DIST, "manifest.webmanifest"), JSON.stringify({
  name: "Rock Team",
  short_name: "Rock Team",
  description: "Practice plans, rotation, roster and exercise library for the climbing team.",
  start_url: base,
  scope: base,
  display: "standalone",
  background_color: "#f6f5f2",
  theme_color: "#2f6f5e",
  icons: [
    { src: base + "icon-192.png", sizes: "192x192", type: "image/png" },
    { src: base + "icon-512.png", sizes: "512x512", type: "image/png" },
  ],
}, null, 2));

let html = readFileSync(join(DIST, "index.html"), "utf8");
html = html.replace("</head>", [
  `<link rel="manifest" href="${base}manifest.webmanifest">`,
  `<link rel="apple-touch-icon" href="${base}apple-touch-icon.png">`,
  `<meta name="apple-mobile-web-app-capable" content="yes">`,
  `<meta name="apple-mobile-web-app-title" content="Rock Team">`,
  "</head>",
].join("\n"));
writeFileSync(join(DIST, "index.html"), html);
copyFileSync(join(DIST, "index.html"), join(DIST, "404.html"));
writeFileSync(join(DIST, ".nojekyll"), ""); // GitHub Pages: serve the _expo folder as-is

const files = walk(DIST)
  .map((p) => relative(DIST, p))
  .filter((f) => !["sw.js", "404.html", "metadata.json", ".nojekyll"].includes(f))
  .map((f) => (f === "index.html" ? base : base + f));
const version = createHash("sha256").update(files.join("|") + html).digest("hex").slice(0, 12);

writeFileSync(join(DIST, "sw.js"), `// generated by scripts/finish-web.mjs — do not edit
const CACHE = "rock-team-${version}";
const FILES = ${JSON.stringify(files)};
const SHELL = ${JSON.stringify(base)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith("rock-team-") && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    // The page itself: use the network when it answers quickly (to pick up new versions),
    // otherwise the cached copy — a gym with one bar of signal shouldn't mean a blank screen.
    e.respondWith((async () => {
      const cached = await caches.match(SHELL, { cacheName: CACHE });
      const network = fetch(req).then((res) => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(SHELL, copy)); }
        return res;
      });
      if (!cached) return network;
      const timeout = new Promise((resolve) => setTimeout(() => resolve(cached), 2500));
      return Promise.race([network.catch(() => cached), timeout]);
    })());
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`);

console.log(`Web app ready in dist/ (base ${base}, ${files.length} files precached for offline use).`);
